---

- name: Install php extensions
  become: true
  apt: pkg=php{{ php_branch_version }}-{{ item }} state=present
  with_items: "{{ php_fpm_extensions }}"

- name: Restart {{ php_fpm_package }}
  become: true
  service: name={{ php_fpm_package }} state=restarted
