---

- include: apt.yml
  tags: [php, php-extensions]

- include: php.yml
  tags: [php]

- name: Check if {{ php_fpm_package }} is installed
  command: dpkg-query -l {{ php_fpm_package }}
  register: dpkg_result
  ignore_errors: true
  tags: [php-extensions]

- include: extensions.yml
  when: dpkg_result.stdout.find('no packages found') == -1
  tags: [php-extensions]
